import { style } from "@vanilla-extract/css";

export const styles = {
	container: style({
		width: "100vw",
		height: "100vh",
		backgroundColor: "#fff",
		backgroundPosition: "center",
		backgroundRepeat: "no-repeat",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 0,
	}),
	card: style({
		maxWidth: 1000,
		width: "100%",
		minHeight: 640,
		borderRadius: 10,
		backgroundColor: "#fff",
		borderWidth: 4,
		borderColor: "#000",
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
		gridTemplateRows: "1fr 1fr",
	}),
	header: style({
		maxWidth: 1000,
		width: "100%",
		height: 64,
		position: "relative",
		zIndex: -1,
	}),
	tab: style({
		display: "flex",
		position: "absolute",
		bottom: -8,
	}),
	tab_item: style({
		height: 56,
		padding: "0 48px",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		fontWeight: "bold",
		alignItems: "center",
		backgroundColor: "#D9D9D9",
		borderWidth: 4,
		borderBottom: "none",
		borderColor: "#000",
		marginRight: -16,
		borderRadius: "12px 12px 0 0",
		fontSize: "1.25rem",
		zIndex: -1,
	}),
	home_button: style({
		position: "absolute",
		right: 0,
		top: 0,
		bottom: 0,
	}),
};
